#ifndef CHARACTERSHEET_WIDGET_GLOBAL_H
#define CHARACTERSHEET_WIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHARACTERSHEET_WIDGET_LIBRARY)
#define CHARACTERSHEET_WIDGET_EXPORT Q_DECL_EXPORT
#else
#define CHARACTERSHEET_WIDGET_EXPORT Q_DECL_IMPORT
#endif
#endif // CHARACTERSHEET_GLOBAL_H
