Document: rolisteam
Title: Debian rolisteam Manual
Author: <insert document author here>
Abstract: This manual describes what rolisteam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rolisteam/rolisteam.sgml.gz

Format: postscript
Files: /usr/share/doc/rolisteam/rolisteam.ps.gz

Format: text
Files: /usr/share/doc/rolisteam/rolisteam.text.gz

Format: HTML
Index: /usr/share/doc/rolisteam/html/index.html
Files: /usr/share/doc/rolisteam/html/*.html
