Document: rolisteam
Title: Debian rolisteam Manual
Author: <insert document author here>
Abstract: This manual describes what rolisteam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rcse/rcse.sgml.gz

Format: postscript
Files: /usr/share/doc/rcse/rcse.ps.gz

Format: text
Files: /usr/share/doc/rcse/rcse.text.gz

Format: HTML
Index: /usr/share/doc/rcse/html/index.html
Files: /usr/share/doc/rcse/html/*.html
