#ifndef FORMULA_GLOBAL_H
#define FORMULA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHARACTERSHEET_FORMULA_LIBRARY)
#define CHARACTERSHEET_FORMULA_EXPORT Q_DECL_EXPORT
#else
#define CHARACTERSHEET_FORMULA_EXPORT Q_DECL_IMPORT
#endif
#endif // FORMULA_GLOBAL_H
