#ifndef CHARACTERSHEET_GLOBAL_H
#define CHARACTERSHEET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHARACTERSHEET_LIBRARY)
#define CHARACTERSHEET_EXPORT Q_DECL_EXPORT
#else
#define CHARACTERSHEET_EXPORT Q_DECL_IMPORT
#endif
#endif // CHARACTERSHEET_GLOBAL_H
