/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DbusAdaptor -a dbusadaptor.h:dbusadaptor.cpp org.rolisteam.server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DbusAdaptor
 */

DbusAdaptor::DbusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

void DbusAdaptor::createEmptyConfigFile(const QString &filepath)
{
    // handle method call local.RolisteamDaemon.createEmptyConfigFile
    QMetaObject::invokeMethod(parent(), "createEmptyConfigFile", Q_ARG(QString, filepath));
}

bool DbusAdaptor::readConfigFile(const QString &in0)
{
    // handle method call local.RolisteamDaemon.readConfigFile
    bool out0;
    QMetaObject::invokeMethod(parent(), "readConfigFile", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

