/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DbusAdaptor -a dbusadaptor.h:dbusadaptor.cpp org.rolisteam.server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSADAPTOR_H
#define DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.RolisteamDaemon
 */
class DbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.RolisteamDaemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.RolisteamDaemon\">\n"
"    <signal name=\"stopped\"/>\n"
"    <method name=\"readConfigFile\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"createEmptyConfigFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"filepath\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DbusAdaptor(QObject *parent);
    virtual ~DbusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void createEmptyConfigFile(const QString &filepath);
    bool readConfigFile(const QString &in0);
Q_SIGNALS: // SIGNALS
    void stopped();
};

#endif
