#ifndef QMLCOMPONENTS_GLOBAL_H
#define QMLCOMPONENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMLCOMPONENTS_LIBRARY)
#define QMLCOMPONENTS_EXPORT Q_DECL_EXPORT
#else
#define QMLCOMPONENTS_EXPORT Q_DECL_IMPORT
#endif
#endif // QMLCOMPONENTS_GLOBAL_H
